### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by zhuangsirui** [Shopify/sarama#1017]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.15.0
Kafka Version: 1.0.0
Go Version: 1.9.2 darwin/amd64

##### Configuration

Default env

##### Logs

```
panic: send on closed channel

goroutine 261 [running]:
vendor/github.com/Shopify/sarama.(*asyncProducer).shutdown(0xc420161110)
        vendor/github.com/Shopify/sarama/async_producer.go:825 +0x1a4
vendor/github.com/Shopify/sarama.(*asyncProducer).(vendor/github.com/Shopify/sarama.shutdown)-fm()
        vendor/github.com/Shopify/sarama/async_producer.go:236 +0x42
vendor/github.com/Shopify/sarama.withRecover(0xc4202406a0)
        vendor/github.com/Shopify/sarama/utils.go:45 +0x51
created by vendor/github.com/Shopify/sarama.(*asyncProducer).AsyncClose
        vendor/github.com/Shopify/sarama/async_producer.go:236 +0xae
```

##### Problem Description

When I call `sarama.SyncProducer.Close`, it panic sometime in another goroutine that I cannot recover it.

**Comment by zhuangsirui** [comment]
That's my fault, I called twice, ignore this issue.
