### ISSUE TITLE
async_producer.go:482 panic

### ISSUE THREAD

**Issue by yyn1110** [Shopify/sarama#1250]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:1.20.0
Kafka Version:0.10
Go Version: 1.10

##### Configuration

What configuration values are you using for Sarama and Kafka?
Kafka configuration use username and password 
Sarama configuration is

var url string
var username string
var password string

func InitConfig(cmd *cobra.Command) {
	cmd.Flags().StringVar(&url, "kafkaurl", "172.172.50.11:9092", "kafka address url")
	cmd.Flags().StringVar(&username, "username", "", "kafka username")
	cmd.Flags().StringVar(&password, "password", "", "kafka password")

}

type KafkaManager struct {
	producer sarama.SyncProducer
}

//创建kafka生产端
func NewKafkaProducer() (*KafkaManager, error) {
	config := sarama.NewConfig()
	//config.Producer.RequiredAcks = sarama.WaitForAll
	config.Producer.Partitioner = sarama.NewManualPartitioner
	config.Producer.RequiredAcks = sarama.WaitForLocal       // Only wait for the leader to ack
	config.Producer.Compression = sarama.CompressionSnappy   // Compress messages
	config.Producer.Flush.Frequency = 500 * time.Millisecond // Flush batches every 500ms
	config.Producer.Return.Successes = true

	config.Net.SASL.Enable=true
	config.Net.SASL.Password = password
	config.Net.SASL.User = username

	err:= config.Validate()
	if err!=nil{
		log.Logger.Warn(err.Error())
	}

	list := strings.Split(url, ",")

	log.Logger.Info("kafka连接 ip: %+v", list)
	producer, err := sarama.NewSyncProducer(list, config)
	if err != nil {
		return nil, err
	}

	manager := new(KafkaManager)
	manager.producer = producer

	return manager, nil
}

//关闭
func (this *KafkaManager) Close() error {
	return this.producer.Close()
}

//发送消息
func (this *KafkaManager) SendMessage(topic string, partitionId int, key string, value string) error {
	defer func() {
		if e := recover(); e != nil {
			err := e.(error)
			fmt.Errorf("kafka_error : %s\n",err.Error())
		}
	}()
	msg := &sarama.ProducerMessage{}
	msg.Topic = topic
	msg.Partition = int32(partitionId)
	msg.Key = sarama.StringEncoder(key)
	msg.Value = sarama.ByteEncoder(value)

	_, _, err := this.producer.SendMessage(msg)
	if err != nil {
		return err
	}

	return nil

}

##### Logs

goroutine 59021 [chan receive, 2913 minutes]:
server/vendor/github.com/Shopify/sarama.(*partitionProducer).dispatch(0xc4213c27e0)
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/async_producer.go:496 +0xda
server/vendor/github.com/Shopify/sarama.(*partitionProducer).(server/vendor/github.com/Shopify/sarama.dispatch)-fm()
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/async_producer.go:482 +0x2a
server/vendor/github.com/Shopify/sarama.withRecover(0xc4203f5910)
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/utils.go:45 +0x43
created by server/vendor/github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/async_producer.go:482 +0x1db

goroutine 10874 [chan receive, 178 minutes]:
server/vendor/github.com/Shopify/sarama.(*partitionProducer).dispatch(0xc4215aeba0)
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/async_producer.go:496 +0xda
server/vendor/github.com/Shopify/sarama.(*partitionProducer).(server/vendor/github.com/Shopify/sarama.dispatch)-fm()
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/async_producer.go:482 +0x2a
server/vendor/github.com/Shopify/sarama.withRecover(0xc4210d8340)
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/utils.go:45 +0x43
created by server/vendor/github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/async_producer.go:482 +0x1db

goroutine 671276 [chan receive]:
server/vendor/github.com/Shopify/sarama.(*partitionProducer).dispatch(0xc4211666c0)
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/async_producer.go:496 +0xda
server/vendor/github.com/Shopify/sarama.(*partitionProducer).(server/vendor/github.com/Shopify/sarama.dispatch)-fm()
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/async_producer.go:482 +0x2a
server/vendor/github.com/Shopify/sarama.withRecover(0xc422d42050)
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/utils.go:45 +0x43
created by server/vendor/github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/async_producer.go:482 +0x1db

goroutine 59034 [chan receive]:
server/vendor/github.com/Shopify/sarama.(*partitionProducer).dispatch(0xc421640900)
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/async_producer.go:496 +0xda
server/vendor/github.com/Shopify/sarama.(*partitionProducer).(server/vendor/github.com/Shopify/sarama.dispatch)-fm()
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/async_producer.go:482 +0x2a
server/vendor/github.com/Shopify/sarama.withRecover(0xc42143c0f0)
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/utils.go:45 +0x43
created by server/vendor/github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
        /home/secmanager/deploy/code/dataexchangev3/src/server/vendor/github.com/Shopify/sarama/async_producer.go:482 +0x1db

goroutine 37545 [IO wait]:
internal/poll.runtime_pollWait(0x7f872d6f97e8, 0x72, 0xc420fb6be8)
        /home/secmanager/deploy/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42002a718, 0x72, 0xffffffffffffff00, 0xc25840, 0xf7b4e8)
        /home/secmanager/deploy/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42002a718, 0xc420387000, 0x1000, 0x1000)
        /home/secmanager/deploy/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42002a700, 0xc420387000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/secmanager/deploy/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc42002a700, 0xc420387000, 0x1000, 0x1000, 0x6, 0xc42002c088, 0xc42002c000)
        /home/secmanager/deploy/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4201ae048, 0xc420387000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/secmanager/deploy/go/src/net/net.go:176 +0x6a
bufio.(*Reader).Read(0xc42152c9c0, 0xc4210860c0, 0x7, 0x7, 0xc420fb6db0, 0x440e77, 0x10)
        /home/secmanager/deploy/go/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0xc234e0, 0xc42152c9c0, 0xc4210860c0, 0x7, 0x7, 0x7, 0x0, 0x0, 0xc420fb6e50)
        /home/secmanager/deploy/go/src/io/io.go:309 +0x86
server/pkg/engine.ParsePackage(0xc234e0, 0xc42152c9c0, 0x0, 0x0, 0x0)
        /home/secmanager/deploy/code/dataexchangev3/src/server/pkg/engine/package.go:190 +0xa5
server/pkg/engine.(*SocketConn).readPackage(0xc4200eb040, 0x0, 0xc4200eb040, 0xc422647610, 0x0)

**Comment by yyn1110** [comment]
sorry  I made a mistake
