### ISSUE TITLE
Multiple consumers in consumer group get claim for the same partition

### ISSUE THREAD

**Issue by aaronlehmann** [Shopify/sarama#1500]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.23.1  | 0.10.1.0 | 1.13.0 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
        kafkaConfig := sarama.NewConfig()
        kafkaConfig.Consumer.Return.Errors = true
        kafkaConfig.Consumer.Offsets.Initial = sarama.OffsetOldest
        kafkaConfig.Consumer.Offsets.Retention = 35 * 24 * time.Hour
        kafkaConfig.Version = sarama.V0_10_2_0
```

##### Problem Description

I am trying to migrate from sarama-cluster. When I start multiple consumers and use the same `groupID` on a topic that only has a single partition, I expected only one of the consumers to receive messages (I believe this was the behavior with `sarama-cluster`). Instead, both consumers appear to receive claims which cover the single partition. This means they both receive the full stream of messages.

I start the two consumers at the same time, on a fresh topic that is just starting to receive messages. The behavior I see is that both consumers receive the messages I produce. They each receive a claim with `Partition() == 0` and `InitialOffset() == -2`.

Please let me know if my expectations are incorrect, or if I'm doing something wrong.

**Comment by FrancoisPoinsot** [comment]
Your expectation is correct. 2 consumers of the same group should not share a partition. One consumer should be inactif if the topic has only 1 partition.

Can you share the output of this command `kafka-consumer-groups --bootstrap-server [ANY_BROKER] --group [YOUR_CONSUMER_GROUP] --describe --members --verbose` ?

Execute it a few time in a row while your consumers are active.

This way we will see exactly which pod is consuming which partition and if somehow this change over time.

**Comment by aaronlehmann** [comment]
@FrancoisPoinsot: It seems like the version of `kafka-consumer-groups` that ships with the very old version of kafka I use for test automation (0.10.1.0) doesn't support `--members` or `--verbose`. I tried running the command several times without those options while running my test case, and got some strange output:

```
root@7fbf113a95c5:/# /opt/kafka_2.11-0.10.1.0/bin/kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --group aaron_postgres_log_consumer_group --describe
Error while executing consumer group command Error reading field 'version': java.nio.BufferUnderflowException
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'version': java.nio.BufferUnderflowException
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:73)
        at org.apache.kafka.clients.consumer.internals.ConsumerProtocol.deserializeAssignment(ConsumerProtocol.java:106)
        at kafka.admin.AdminClient$$anonfun$describeConsumerGroup$1.apply(AdminClient.scala:156)
        at kafka.admin.AdminClient$$anonfun$describeConsumerGroup$1.apply(AdminClient.scala:155)
        at scala.collection.immutable.List.map(List.scala:277)
        at kafka.admin.AdminClient.describeConsumerGroup(AdminClient.scala:155)
        at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService.describeGroup(ConsumerGroupCommand.scala:308)
        at kafka.admin.ConsumerGroupCommand$ConsumerGroupService$class.describe(ConsumerGroupCommand.scala:89)
        at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService.describe(ConsumerGroupCommand.scala:296)
        at kafka.admin.ConsumerGroupCommand$.main(ConsumerGroupCommand.scala:68)
        at kafka.admin.ConsumerGroupCommand.main(ConsumerGroupCommand.scala)

root@7fbf113a95c5:/# /opt/kafka_2.11-0.10.1.0/bin/kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --group aaron_postgres_log_consumer_group --describe
GROUP                          TOPIC                          PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             OWNER
aaron_postgres_log_consumer_group log_stream_aaron               0          17494           17494           0               176c1760-9269-4c55-b21d-265985f4a303_/10.0.135.129
root@7fbf113a95c5:/# /opt/kafka_2.11-0.10.1.0/bin/kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --group aaron_postgres_log_consumer_group --describe
Consumer group `aaron_postgres_log_consumer_group` is rebalancing.
root@7fbf113a95c5:/# /opt/kafka_2.11-0.10.1.0/bin/kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --group aaron_postgres_log_consumer_group --describe
Error while executing consumer group command Error reading field 'version': java.nio.BufferUnderflowException
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'version': java.nio.BufferUnderflowException
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:73)
        at org.apache.kafka.clients.consumer.internals.ConsumerProtocol.deserializeAssignment(ConsumerProtocol.java:106)
        at kafka.admin.AdminClient$$anonfun$describeConsumerGroup$1.apply(AdminClient.scala:156)
        at kafka.admin.AdminClient$$anonfun$describeConsumerGroup$1.apply(AdminClient.scala:155)
        at scala.collection.immutable.List.map(List.scala:277)
        at kafka.admin.AdminClient.describeConsumerGroup(AdminClient.scala:155)
        at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService.describeGroup(ConsumerGroupCommand.scala:308)
        at kafka.admin.ConsumerGroupCommand$ConsumerGroupService$class.describe(ConsumerGroupCommand.scala:89)
        at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService.describe(ConsumerGroupCommand.scala:296)
        at kafka.admin.ConsumerGroupCommand$.main(ConsumerGroupCommand.scala:68)
        at kafka.admin.ConsumerGroupCommand.main(ConsumerGroupCommand.scala)

root@7fbf113a95c5:/# /opt/kafka_2.11-0.10.1.0/bin/kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --group aaron_postgres_log_consumer_group --describe
Consumer group `aaron_postgres_log_consumer_group` is rebalancing.
root@7fbf113a95c5:/# /opt/kafka_2.11-0.10.1.0/bin/kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --group aaron_postgres_log_consumer_group --describe
Consumer group `aaron_postgres_log_consumer_group` is rebalancing.
root@7fbf113a95c5:/# /opt/kafka_2.11-0.10.1.0/bin/kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --group aaron_postgres_log_consumer_group --describe
Consumer group `aaron_postgres_log_consumer_group` is rebalancing.
root@7fbf113a95c5:/# /opt/kafka_2.11-0.10.1.0/bin/kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --group aaron_postgres_log_consumer_group --describe
Consumer group `aaron_postgres_log_consumer_group` is rebalancing.
root@7fbf113a95c5:/# /opt/kafka_2.11-0.10.1.0/bin/kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --group aaron_postgres_log_consumer_group --describe
Consumer group `aaron_postgres_log_consumer_group` is rebalancing.
root@7fbf113a95c5:/# /opt/kafka_2.11-0.10.1.0/bin/kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --group aaron_postgres_log_consumer_group --describe
Consumer group `aaron_postgres_log_consumer_group` is rebalancing.
root@7fbf113a95c5:/# /opt/kafka_2.11-0.10.1.0/bin/kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --group aaron_postgres_log_consumer_group --describe
Consumer group `aaron_postgres_log_consumer_group` is rebalancing.
root@7fbf113a95c5:/# /opt/kafka_2.11-0.10.1.0/bin/kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --group aaron_postgres_log_consumer_group --describe
GROUP                          TOPIC                          PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             OWNER
aaron_postgres_log_consumer_group log_stream_aaron               0          17494           17494           0               535c443b-a05f-438b-aaa7-b741325b2cc1_/10.0.135.129
```

This is a run every few seconds over the course of about 20 seconds.

**Comment by FrancoisPoinsot** [comment]
Assuming you did not close/restarted any consumer during this test, I think I saw what I was looking for.
The reason it looks like both your consumers reads the same partition is that they are rebalancing way too often.

In truth, when you rebalance that often, they might be a lot of your messages that are actually consumed and processed by both consumers.

Now remains the reason why you are rebalancing. 

I suggest 2 things:
1) setup the sarama.Logger to see debug `sarama.logger = log.New(os.Stderr, "", log.LstdFlags)`

2) I noticed your broker version is 0.10.1 but the sarama version in your config is 0.10.2
I remember the version 0.10.2 of kafka bring huge differences. I suggest you to either upgrade your broker or downgrad the kafkaConfig.version to 0.10.1

**Comment by aaronlehmann** [comment]
@FrancoisPoinsot: Trying to set `kafkaConfig.Version` to V0_10_1_0 gives me:

```
kafka: invalid configuration (consumer groups require Version to be >= V0_10_2_0)
```

Upgrading kafka may well be the answer. I've been using the `shopify/kafka` all-in-one Docker container for this testing use case. I'll need to look around for a newer container image.

**Comment by FrancoisPoinsot** [comment]
I used this one: https://github.com/Landoop/fast-data-dev
you can find a tag for every version up to the recent ones.

**Comment by DennisMao** [comment]
@aaronlehmann   [wurstmeister/kafka](https://github.com/wurstmeister/kafka-docker)  can do so.
