### ISSUE TITLE
Error from consumer: dial tcp 127.0.0.1:9092 when im set external ip in broker variable

### ISSUE THREAD

**Issue by daviresio** [Shopify/sarama#1598]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  v1.26.0|  2.2.2| 1.13 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` package main

import (
	"context"
	"flag"
	"log"
	"os"
	"os/signal"
	"strings"
	"sync"
	"syscall"

	"github.com/Shopify/sarama"
)

// Sarama configuration options
var (
	brokers  = "35.208.219.148:9092"
	version  = "2.2.2"
	group    = "consumer-group-grupo"
	topics   = "database-1.public.grupo"
	assignor = ""
	oldest   = true
	verbose  = false
)

func init() {
	flag.StringVar(&brokers, "brokers", "35.208.219.148:9092", "Kafka bootstrap brokers to connect to, as a comma separated list")
	flag.StringVar(&group, "group", "consumer-group-grupo", "Kafka consumer group definition")
	flag.StringVar(&version, "version", "2.2.2", "Kafka cluster version")
	flag.StringVar(&topics, "topics", "database-1.public.grupo", "Kafka topics to be consumed, as a comma seperated list")
	flag.StringVar(&assignor, "assignor", "range", "Consumer group partition assignment strategy (range, roundrobin, sticky)")
	flag.BoolVar(&oldest, "oldest", true, "Kafka consumer consume initial offset from oldest")
	flag.BoolVar(&verbose, "verbose", false, "Sarama logging")
	flag.Parse()

	if len(brokers) == 0 {
		panic("no Kafka bootstrap brokers defined, please set the -brokers flag")
	}

	if len(topics) == 0 {
		panic("no topics given to be consumed, please set the -topics flag")
	}

	if len(group) == 0 {
		panic("no Kafka consumer group defined, please set the -group flag")
	}
}

func main() {
	log.Println("Starting a new Sarama consumer")
	if verbose {
		sarama.Logger = log.New(os.Stdout, "[sarama] ", log.LstdFlags)
	}

	version, err := sarama.ParseKafkaVersion(version)
	if err != nil {
		log.Panicf("Error parsing Kafka version: %v", err)
	}

	/**
	 * Construct a new Sarama configuration.
	 * The Kafka cluster version has to be defined before the consumer/producer is initialized.
	 */
	config := sarama.NewConfig()
	config.Version = version

	switch assignor {
	case "sticky":
		config.Consumer.Group.Rebalance.Strategy = sarama.BalanceStrategySticky
	case "roundrobin":
		config.Consumer.Group.Rebalance.Strategy = sarama.BalanceStrategyRoundRobin
	case "range":
		config.Consumer.Group.Rebalance.Strategy = sarama.BalanceStrategyRange
	default:
		log.Panicf("Unrecognized consumer group partition assignor: %s", assignor)
	}

	if oldest {
		config.Consumer.Offsets.Initial = sarama.OffsetOldest
	}

	/**
	 * Setup a new Sarama consumer group
	 */
	consumer := Consumer{
		ready: make(chan bool),
	}

	ctx, cancel := context.WithCancel(context.Background())
	client, err := sarama.NewConsumerGroup(strings.Split(brokers, ","), group, config)
	if err != nil {
		log.Panicf("Error creating consumer group client: %v", err)
	}

	wg := &sync.WaitGroup{}
	wg.Add(1)
	go func() {
		defer wg.Done()
		for {
			if err := client.Consume(ctx, strings.Split(topics, ","), &consumer); err != nil {
				log.Panicf("Error from consumer: %v", err)
			}
			// check if context was cancelled, signaling that the consumer should stop
			if ctx.Err() != nil {
				return
			}
			consumer.ready = make(chan bool)
		}
	}()

	<-consumer.ready // Await till the consumer has been set up
	log.Println("Sarama consumer up and running!...")

	sigterm := make(chan os.Signal, 1)
	signal.Notify(sigterm, syscall.SIGINT, syscall.SIGTERM)
	select {
	case <-ctx.Done():
		log.Println("terminating: context cancelled")
	case <-sigterm:
		log.Println("terminating: via signal")
	}
	cancel()
	wg.Wait()
	if err = client.Close(); err != nil {
		log.Panicf("Error closing client: %v", err)
	}
}

// Consumer represents a Sarama consumer group consumer
type Consumer struct {
	ready chan bool
}

// Setup is run at the beginning of a new session, before ConsumeClaim
func (consumer *Consumer) Setup(sarama.ConsumerGroupSession) error {
	// Mark the consumer as ready
	close(consumer.ready)
	return nil
}

// Cleanup is run at the end of a session, once all ConsumeClaim goroutines have exited
func (consumer *Consumer) Cleanup(sarama.ConsumerGroupSession) error {
	return nil
}

// ConsumeClaim must start a consumer loop of ConsumerGroupClaim's Messages().
func (consumer *Consumer) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {

	// NOTE:
	// Do not move the code below to a goroutine.
	// The `ConsumeClaim` itself is called within a goroutine, see:
	// https://github.com/Shopify/sarama/blob/master/consumer_group.go#L27-L29
	for message := range claim.Messages() {
		log.Printf("Message claimed: value = %s, timestamp = %v, topic = %s", string(message.Value), message.Timestamp, message.Topic)
		session.MarkMessage(message, "")
	}

	return nil
}
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
GOROOT=/usr/local/lib/go #gosetup
GOPATH=/home/davi/go #gosetup
/usr/local/lib/go/bin/go build -o /tmp/___go_build_github_com_daviresio_sync_database github.com/daviresio/sync-database #gosetup
/tmp/___go_build_github_com_daviresio_sync_database #gosetup
2020/02/01 21:08:56 Starting a new Sarama consumer
2020/02/01 21:08:56 Error from consumer: dial tcp 127.0.0.1:9092: connect: connection refused
panic: Error from consumer: dial tcp 127.0.0.1:9092: connect: connection refused

goroutine 11 [running]:
log.Panicf(0x88851c, 0x17, 0xc0000e9f90, 0x1, 0x1)
        /usr/local/lib/go/src/log/log.go:345 +0xc0
main.main.func1(0xc000020ac0, 0x919160, 0xc0000e41b0, 0x91a1e0, 0xc0000782c0, 0xc000010060)
        /home/davi/go/src/github.com/daviresio/sync-database/main.go:102 +0x17f
created by main.main
        /home/davi/go/src/github.com/daviresio/sync-database/main.go:98 +0x3e2

Process finished with exit code 2

```

</p>
</details>

##### Problem Description

hi, im try run example consumer found here https://github.com/Shopify/sarama/tree/master/examples/consumergroup with my kafka run on GCP instance.

im set correct ip for broker variable, im set in initialization, in flag flag.StringVar and in terminal

go run main.go -brokers="35.208.219.148:9092" -topics="database-1.public.grupo" -group="consumer-group-grupo"

but im get error like if im try run on localhost:
 Error from consumer: dial tcp 127.0.0.1:9092

im print the broker variable before code broken and the ip is set correct
have any way to connect consumer to a external ip?

sorry for any mistake, im newbe on kafka and GO

**Comment by daviresio** [comment]
i see i need define on my image on ec2 instance the ip of host, sorry

**Comment by PearceDuan** [comment]
can you explain more detail? I meet the same problem now. much thanks! @daviresio

**Comment by PearceDuan** [comment]
After some research, it's a config problem on server side, 

For kafka version 2.3.0: 
vim config/server.properties
```
listeners=PLAINTEXT://0.0.0.0:9092
advertised.listeners=PLAINTEXT://192.168.130.63:9092
```
After restart the broker, than you can connect broker both over localhost:9092 and 192.168.130.63:9092

**Comment by Sen-Gupta** [comment]
> PLAINTEXT://192.168.130.63:9092

This steered me in the correct direction!.
Thanks!
