### ISSUE TITLE
[QUESTION] - Sarama ConsumerGroup not connecting to Bitnami/Kafka 2.7.0 

### ISSUE THREAD

**Issue by NZenitram** [Shopify/sarama#1868]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.27.2 | 2.7.0 | 1.14  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
	c := sarama.NewConfig()
	c.Version = sarama.V2_6_0_0
```
Loop Stanza: 

```
type KafkaConfig struct {
    host     string      ## kafka-headless.bitnami-kafka:9092
    topic    string      ## testing28-webhookrelay-io
    group    string    ## testing28-webhookrelay-io
    producer sarama.AsyncProducer
    consumer sarama.Consumer
    useJSON  bool
}

i := &KafkaInput{
		ConsumerGroup: group,
		config:        config,
		messages:      make(chan *sarama.ConsumerMessage, 256),
		consumer:      consumer,
	}


func (i *KafkaInput) loop(topic []string) {
	log.Println("KafkaInput: %d", i)
	ctx := context.Background()
	for {
		if err := i.Consume(ctx, []string{i.config.topic}, i); err != nil {
			if err != nil {
				log.Panicf("Error in loop: %v", err)
			}
			return
		}
	}
}
```

This is deployed in a Kubernetes cluster and is being accessed by a kubernetes service. 
`kafka-headless.bitnami-kafka:9092`

The producers can access and right to the topic at this address. The SaramaGroupConsumer appear to be unable to. 

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
2021/01/04 18:17:40 KafkaConfigHost: kafka-headless.bitnami-kafka:9092
2021/01/04 18:17:40 KafkaConfigGroup: testing28-webhookrelay-io
2021/01/04 18:17:40 KafkaConfigTopic: testing28-webhookrelay-io
2021/01/04 18:17:40 Starting a new Sarama consumer
Version:
2021/01/04 18:17:40 KafkaInput: %d Kafka Input: kafka-headless.bitnami-kafka:9092/testing28-webhookrelay-io
2021/01/04 18:17:40 Error in loop: dial tcp: lookup kafka-2.kafka-headless.bitnami-kafka.svc.cluster.local: device or resource busy
panic: Error in loop: dial tcp: lookup kafka-2.kafka-headless.bitnami-kafka.svc.cluster.local: device or resource busy

goroutine 38 [running]:
log.Panicf(0xc0b74a, 0x11, 0xc000101f80, 0x1, 0x1)
 /usr/local/go/src/log/log.go:358 +0xc0
main.(*KafkaInput).loop(0xc00007d860, 0xc00003e960, 0x1, 0x1)
 /app/input_kafka.go:120 +0x189
created by main.NewKafkaInput
 /app/input_kafka.go:100 +0x4b6
```

</p>
</details>

##### Problem Description

This configuration was working prior to a Chart change and upgrade where the Version Sarama defined was 2.1.1. I realize I am outside the band of the support Kafka version and maybe that is the only problem here. The Sarama producers I am using connect to the new cluster, as do the test consumer pods and consumers I have written using the Confluent go package. However, for some reason this consumer group configuration has broken. The TCP Lookup URL also has been confused as it is missing the port. 

This may not be related to the Sarama consumer at all but I dont know where else to turn after debugging for quite some time. Maybe someone can point me in the right direction. 

Regarding Versioning: I know I was using the incorrect version in the previous configuration and it worked fine. 

Thanks

**Comment by NZenitram** [comment]
When I update the host to the list of internal listeners, I get the same error. I believe this may be an internal configuration problem: 
Host list: `kafka-0.kafka-headless.bitnami-kafka:9092,kafka-1.kafka-headless.bitnami-kafka:9092`
Error: `Error in loop: dial tcp: lookup kafka-2.kafka-headless.bitnami-kafka.svc.cluster.local: device or resource busy`


```
host string: %d [kafka-0.kafka-headless.bitnami-kafka:9092 kafka-1.kafka-headless.bitnami-kafka:9092]
2021/01/04 21:38:06 KafkaConfigHost: kafka-0.kafka-headless.bitnami-kafka:9092,kafka-1.kafka-headless.bitnami-kafka:9092
2021/01/04 21:38:06 KafkaConfigGroup: testing28-webhookrelay-io
2021/01/04 21:38:06 KafkaConfigTopic: testing28-webhookrelay-io
2021/01/04 21:38:06 Starting a new Sarama consumer
Version:
2021/01/04 21:38:11 KafkaInput: %d Kafka Input: kafka-0.kafka-headless.bitnami-kafka:9092,kafka-1.kafka-headless.bitnami-kafka:9092/testing28-webhookrelay-io
2021/01/04 21:38:11 Error in loop: dial tcp: lookup kafka-2.kafka-headless.bitnami-kafka.svc.cluster.local: device or resource busy
panic: Error in loop: dial tcp: lookup kafka-2.kafka-headless.bitnami-kafka.svc.cluster.local: device or resource busy

goroutine 30 [running]:
log.Panicf(0xc0b759, 0x11, 0xc00005ef80, 0x1, 0x1)
 /usr/local/go/src/log/log.go:358 +0xc0
main.(*KafkaInput).loop(0xc0001c09f0, 0xc0000996a0, 0x1, 0x1)
 /app/input_kafka.go:122 +0x189
created by main.NewKafkaInput
 /app/input_kafka.go:102 +0x581
```

**Comment by NZenitram** [comment]
Example Broker Configuration: 

```
############################# Server Basics #############################

# The id of the broker. This must be set to a unique integer for each broker.
broker.id=0

############################# Socket Server Settings #############################

# The address the socket server listens on. It will get the value returned from 
# java.net.InetAddress.getCanonicalHostName() if not configured.
#   FORMAT:
#     listeners = listener_name://host_name:port
#   EXAMPLE:
#     listeners = PLAINTEXT://your.host.name:9092
listeners=INTERNAL://:9093,CLIENT://:9092

# Hostname and port the broker will advertise to producers and consumers. If not set, 
# it uses the value for "listeners" if configured.  Otherwise, it will use the value
# returned from java.net.InetAddress.getCanonicalHostName().
advertised.listeners=INTERNAL://kafka-0.kafka-headless.bitnami-kafka.svc.cluster.local:9093,CLIENT://kafka-0.kafka-headless.bitnami-kafka.svc.cluster.local:9092

# Maps listener names to security protocols, the default is for them to be the same. See the config documentation for more details
listener.security.protocol.map=INTERNAL:SASL_PLAINTEXT,CLIENT:PLAINTEXT

# The number of threads that the server uses for receiving requests from the network and sending responses to the network
num.network.threads=3

# The number of threads that the server uses for processing requests, which may include disk I/O
num.io.threads=8

# The send buffer (SO_SNDBUF) used by the socket server
socket.send.buffer.bytes=102400

# The receive buffer (SO_RCVBUF) used by the socket server
socket.receive.buffer.bytes=102400

# The maximum size of a request that the socket server will accept (protection against OOM)
socket.request.max.bytes=104857600
```

**Comment by NZenitram** [comment]
The consumer connects to this Kafka Cluster deployed in the cluster https://github.com/helm/charts/tree/master/incubator/kafka but no the Bitnami cluster. I am still investigating this but have confirmed this is the case by installing both clusters and connecting to each.

**Comment by NZenitram** [comment]
I have reverted for the confluent kafka image from the deprecated helm chart. Still not entirely sure what the bitnami one doesnt work with this Consumer.
