### ISSUE TITLE
sarama client panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by handsomewwu** [Shopify/sarama#1920]
sarama version: v1.26.1

sarama will panic at client.go:533 while fetching metadata when the client is closed

![image](https://user-images.githubusercontent.com/56934543/116037657-fd503a80-a69a-11eb-8b8f-4f8c90d85458.png)

client.brokers will be nil when the client is closed, but sarama does not check if client.brokers is nil before  client.go:533
![image](https://user-images.githubusercontent.com/56934543/116038072-89626200-a69b-11eb-8e47-f87a1273abc9.png)

**Comment by handsomewwu** [comment]
panic: assignment to entry in nil map
goroutine 1393273 [running]:
github.com/Shopify/sarama.(*client).registerBroker(0xc00001e750, 0xc001c69500)
/data/landun/workspace/xg_go/vendor/github.com/Shopify/sarama/client.go:533 +0x2cb
github.com/Shopify/sarama.(*client).updateMetadata(0xc00001e750, 0xc00064b8b0, 0xc00064b800, 0x0, 0x0, 0x0)
/data/landun/workspace/xg_go/vendor/github.com/Shopify/sarama/client.go:844 +0xd5
github.com/Shopify/sarama.(*client).tryRefreshMetadata(0xc00001e750, 0xc001b61b10, 0x1, 0x1, 0x3, 0x0, 0x0, 0x0, 0x10, 0x7f6e50502e98)
/data/landun/workspace/xg_go/vendor/github.com/Shopify/sarama/client.go:789 +0x82d
github.com/Shopify/sarama.(*client).RefreshMetadata(0xc00001e750, 0xc001b61b10, 0x1, 0x1, 0x1d693212d88835, 0xc00064b818)
/data/landun/workspace/xg_go/vendor/github.com/Shopify/sarama/client.go:442 +0xb0
github.com/Shopify/sarama.(*consumerGroup).topicToPartitionNumbers(0xc00001e7e0, 0xc001b61b10, 0x1, 0x1, 0x0, 0x7000102, 0x0)
/data/landun/workspace/xg_go/vendor/github.com/Shopify/sarama/consumer_group.go:472 +0x72
github.com/Shopify/sarama.(*consumerGroup).loopCheckPartitionNumbers(0xc00001e7e0, 0xc001b61b10, 0x1, 0x1, 0xc000337600)
/data/landun/workspace/xg_go/vendor/github.com/Shopify/sarama/consumer_group.go:450 +0xe0
created by github.com/Shopify/sarama.(*consumerGroup).Consume
/data/landun/workspace/xg_go/vendor/github.com/Shopify/sarama/consumer_group.go:178 +0x232
