### ISSUE TITLE
Bug? abnormal restart. unlock of unlocked mutex 

### ISSUE THREAD

**Issue by yalay** [Shopify/sarama#2075]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|v1.29.0|-------|1.3|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs
fatal error: sync: unlock of unlocked mutex
goroutine 3381274 [running]:
runtime.throw(0xe5942f, 0x1e)
/usr/lib/golang/src/runtime/panic.go:1116 +0x72 fp=0xc00141b618 sp=0xc00141b5e8 pc=0x439932
sync.throw(0xe5942f, 0x1e)
/usr/lib/golang/src/runtime/panic.go:1102 +0x35 fp=0xc00141b638 sp=0xc00141b618 pc=0x46cc55
sync.(*Mutex).unlockSlow(0x1690cf0, 0xc0ffffffff)
/usr/lib/golang/src/sync/mutex.go:196 +0xd8 fp=0xc00141b660 sp=0xc00141b638 pc=0x47d098
sync.(*Mutex).Unlock(0x1690cf0)
/usr/lib/golang/src/sync/mutex.go:190 +0x48 fp=0xc00141b680 sp=0xc00141b660 pc=0x47cfa8
sync.(*Pool).pinSlow(0x165d9a0, 0xc000e96280, 0x5)
/usr/lib/golang/src/sync/pool.go:230 +0x167 fp=0xc00141b700 sp=0xc00141b680 pc=0x47d867
sync.(*Pool).pin(0x165d9a0, 0xc00987efd0, 0x7fac541282c0)
/usr/lib/golang/src/sync/pool.go:206 +0x65 fp=0xc00141b728 sp=0xc00141b700 pc=0x47d6c5
sync.(*Pool).Get(0x165d9a0, 0x0, 0x0)
/usr/lib/golang/src/sync/pool.go:128 +0x2f fp=0xc00141b770 sp=0xc00141b728 pc=0x47d36f
github.com/Shopify/sarama.acquireLengthField(...)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/length_field.go:17
github.com/Shopify/sarama.(*MessageBlock).decode(0xc00987efd0, 0xf69ba0, 0xc000d04b40, 0x0, 0x0)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/message_set.go:32 +0x85 fp=0xc00141b7c0 sp=0xc00141b770 pc=0xc1a205
github.com/Shopify/sarama.(*MessageSet).decode(0xc000481b60, 0xf69ba0, 0xc000d04b40, 0x0, 0x0)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/message_set.go:85 +0xf0 fp=0xc00141b830 sp=0xc00141b7c0 pc=0xc1a5f0
github.com/Shopify/sarama.(*Message).decodeSet(0xc00328b830, 0xc0030aa057, 0x81e0)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/message.go:167 +0xc5 fp=0xc00141b888 sp=0xc00141b830 pc=0xc19f05
github.com/Shopify/sarama.(*Message).decode(0xc00328b830, 0xf69ba0, 0xc0066fc580, 0x0, 0x0)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/message.go:155 +0x348 fp=0xc00141b910 sp=0xc00141b888 pc=0xc19bc8
github.com/Shopify/sarama.(*MessageBlock).decode(0xc0020f2840, 0xf69ba0, 0xc0066fc580, 0x0, 0x0)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/message_set.go:40 +0x151 fp=0xc00141b960 sp=0xc00141b910 pc=0xc1a2d1
github.com/Shopify/sarama.(*MessageSet).decode(0xc0008c24c0, 0xf69ba0, 0xc0066fc580, 0x0, 0x0)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/message_set.go:85 +0xf0 fp=0xc00141b9d0 sp=0xc00141b960 pc=0xc1a5f0
github.com/Shopify/sarama.(*Records).decode(0xc0008c24a0, 0xf69ba0, 0xc0066fc580, 0xc0066fc580, 0x0)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/records.go:92 +0x179 fp=0xc00141ba28 sp=0xc00141b9d0 pc=0xc2c3d9
github.com/Shopify/sarama.(*FetchResponseBlock).decode(0xc00043b340, 0xf69ba0, 0xc0066fc540, 0x3, 0xc001133408, 0xc001c06be0)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/fetch_response.go:110 +0x1e5 fp=0xc00141bac8 sp=0xc00141ba28 pc=0xc0df05
github.com/Shopify/sarama.(*FetchResponse).decode(0xc001795e40, 0xf69ba0, 0xc0066fc540, 0xd20003, 0xdfde60, 0xc001138700)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/fetch_response.go:284 +0x159 fp=0xc00141bb50 sp=0xc00141bac8 pc=0xc0ec39
github.com/Shopify/sarama.versionedDecode(0xc0030aa000, 0x8237, 0x8237, 0x7fac54d28498, 0xc001795e40, 0x3, 0x0, 0xdcfee0)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/encoder_decoder.go:84 +0xb5 fp=0xc00141bb98 sp=0xc00141bb50 pc=0xc0ac75
github.com/Shopify/sarama.(*Broker).sendAndReceive(0xc001138700, 0xf5f540, 0xc001795e00, 0xf5f5a0, 0xc001795e40, 0xc000a230b0, 
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/broker.go:796 +0x245 fp=0xc00141bc88 sp=0xc00141bb98 pc=0xbe6e85
github.com/Shopify/sarama.(*Broker).Fetch(0xc001138700, 0xc001795e00, 0xc00000008f, 0xc0003e2958, 0xc0019b1e98)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/broker.go:352 +0x70 fp=0xc00141bcd8 sp=0xc00141bc88 pc=0xbe4890
github.com/Shopify/sarama.(*brokerConsumer).fetchNewMessages(0xc001ab11d0, 0x0, 0x0, 0x0)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/consumer.go:943 +0x749 fp=0xc00141bea8 sp=0xc00141bcd8 pc=0xbfd9e9
github.com/Shopify/sarama.(*brokerConsumer).subscriptionConsumer(0xc001ab11d0)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/consumer.go:800 +0x125 fp=0xc00141bfa0 sp=0xc00141bea8 pc=0xbfc045
github.com/Shopify/sarama.(*brokerConsumer).subscriptionConsumer-fm()
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/consumer.go:787 +0x2a fp=0xc00141bfb8 sp=0xc00141bfa0 pc=0xc3892a
github.com/Shopify/sarama.withRecover(0xc00112abf0)
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/utils.go:43 +0x49 fp=0xc00141bfd8 sp=0xc00141bfb8 pc=0xc310e9
runtime.goexit()
/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00141bfe0 sp=0xc00141bfd8 pc=0x471c61
created by github.com/Shopify/sarama.(*consumer).newBrokerConsumer
/Code/pkg/mod/github.com/!shopify/sarama@v1.29.0/consumer.go:741 +0x1a5

##### Problem Description
restart abnormal and can not recover

**Comment by yalay** [comment]
> @yalay just to check, Go 1.3 as-in the one from 2014?
> 
> Sarama's only involvement in this panic is that we call a [sync.Pool](https://golang.org/pkg/sync/#Pool) related method in the core library and expect it to perform as per its declaration, but it looks like it ends up panic'ing because the lock+unlock tracking of its internal mutexes has gone wrong somewhere. I'm assuming whatever caused you to get into this state has been fixed in subsequent versions of Go as this area has had various [changes](https://github.com/golang/go/blame/0e1d553b4d98b71799b86b0ba9bc338de29b7dfe/src/sync/pool.go#L209-L231) in the last 7 years
> 
> Unfortunately there's not much else we can do from a Sarama perspective to help. I'd strongly recommend that you look at upgrading to one of the supported versions (1.16 / 1.17) of Go from https://go.dev/dl/

my mistake. go version is 1.13. 2019 year release.
test on go version 1.15，but the same phenomenon.

**Comment by dnwe** [comment]
hmm that's odd

**Comment by dnwe** [comment]
@yalay please can you build and run your application with the [race detector](https://go.dev/blog/race-detector) enabled and post the output?

**Comment by yalay** [comment]
#

> @yalay please can you build and run your application with the [race detector](https://go.dev/blog/race-detector) enabled and post the output?

thanks dnwe. We check our code first and feedback if problem still exist.
