### ISSUE TITLE
producer panic when retrying send the message

### ISSUE THREAD

**Issue by wrfly** [Shopify/sarama#2322]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.35.0 |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
Producer.Retry.Max = 3 (default)
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
2022/08/24 11:49:01 kafka: Failed to produce message to topic xxxx_kwad_ph_log_live: circuit breaker is open
2022/08/24 11:49:01 kafka: Failed to produce message to topic xxxx_kwad_ph_log_live: circuit breaker is open
2022/08/24 11:49:01 kafka: Failed to produce message to topic xxxx_kwad_ph_log_live: circuit breaker is open
2022/08/24 11:49:01 kafka: Failed to produce message to topic xxxx_kwad_ph_log_live: circuit breaker is open
2022/08/24 11:49:01 kafka: Failed to produce message to topic xxxx_kwad_log_live: kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes
2022/08/24 11:49:01 kafka: Failed to produce message to topic xxxx_kwad_log_live: kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes
2022/08/24 11:49:01 kafka: Failed to produce message to topic xxxx_kwad_log_live: kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes
2022/08/24 11:49:01 kafka: Failed to produce message to topic xxxx_kwad_log_live: kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes
2022/08/24 11:49:01 kafka: Failed to produce message to topic xxxx_kwad_log_live: kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes
2022/08/24 11:49:01 kafka: Failed to produce message to topic xxxx_kwad_log_live: kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x936fbd]

goroutine 127982 [running]:
github.com/Shopify/sarama.(*partitionProducer).newHighWatermark(0xc93a0bc480, 0x1)
    /root/go/pkg/mod/github.com/!shopify/sarama@v1.35.0/async_producer.go:620 +0x19d
github.com/Shopify/sarama.(*partitionProducer).dispatch(0xc93a0bc480)
    /root/go/pkg/mod/github.com/!shopify/sarama@v1.35.0/async_producer.go:564 +0x50a
github.com/Shopify/sarama.withRecover(0xc93a0ac510?)
    /root/go/pkg/mod/github.com/!shopify/sarama@v1.35.0/utils.go:43 +0x3e
created by github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
    /root/go/pkg/mod/github.com/!shopify/sarama@v1.35.0/async_producer.go:515 +0x1f6
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x936fbd]

goroutine 216212 [running]:
github.com/Shopify/sarama.(*partitionProducer).newHighWatermark(0xca56562ea0, 0x2)
    /root/go/pkg/mod/github.com/!shopify/sarama@v1.35.0/async_producer.go:620 +0x19d
github.com/Shopify/sarama.(*partitionProducer).dispatch(0xca56562ea0)
    /root/go/pkg/mod/github.com/!shopify/sarama@v1.35.0/async_producer.go:564 +0x50a
github.com/Shopify/sarama.withRecover(0xca55e1c6c0?)
    /root/go/pkg/mod/github.com/!shopify/sarama@v1.35.0/utils.go:43 +0x3e
created by github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
    /root/go/pkg/mod/github.com/!shopify/sarama@v1.35.0/async_producer.go:515 +0x1f6
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x936fbd]

goroutine 168736 [running]:
github.com/Shopify/sarama.(*partitionProducer).newHighWatermark(0xc9ce48f8c0, 0x1)
    /root/go/pkg/mod/github.com/!shopify/sarama@v1.35.0/async_producer.go:620 +0x19d
github.com/Shopify/sarama.(*partitionProducer).dispatch(0xc9ce48f8c0)
    /root/go/pkg/mod/github.com/!shopify/sarama@v1.35.0/async_producer.go:564 +0x50a
github.com/Shopify/sarama.withRecover(0xc9c7e7b1d0?)
    /root/go/pkg/mod/github.com/!shopify/sarama@v1.35.0/utils.go:43 +0x3e
created by github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
```

</p>
</details>

##### Problem Description

producer panic when Kafka cluster has no partition leader

```
goroutine 168736 [running]:
github.com/Shopify/sarama.(*partitionProducer).newHighWatermark(0xc9ce48f8c0, 0x1)
    /root/go/pkg/mod/github.com/!shopify/sarama@v1.35.0/async_producer.go:620 +0x19d
github.com/Shopify/sarama.(*partitionProducer).dispatch(0xc9ce48f8c0)
    /root/go/pkg/mod/github.com/!shopify/sarama@v1.35.0/async_producer.go:564 +0x50a
github.com/Shopify/sarama.withRecover(0xc9c7e7b1d0?)
    /root/go/pkg/mod/github.com/!shopify/sarama@v1.35.0/utils.go:43 +0x3e
created by github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
```

related code:

https://github.com/Shopify/sarama/blob/main/async_producer.go#L564

https://github.com/Shopify/sarama/blob/3083a9b96a628fcb0882de334507af5e520ca1cb/async_producer.go#L620

need to check the `brokerProducer` before send message (no matter normal send or retry)

https://github.com/Shopify/sarama/blob/3083a9b96a628fcb0882de334507af5e520ca1cb/async_producer.go#L612-L626

**Comment by BarbarossaTM** [comment]
Just hit the same issue. It feels like a race condition from what we are seeing, but we didn't look very deeply into it. Did anyone already debug this? :-)

**Comment by 3AceShowHand** [comment]
The same problem also happens to `v1.36.0`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11220c9]

goroutine 217306 [running]:
github.com/Shopify/sarama.(*partitionProducer).newHighWatermark(0xc410f81d40, 0x1)
	github.com/Shopify/sarama@v1.36.0/async_producer.go:620 +0x1a9
github.com/Shopify/sarama.(*partitionProducer).dispatch(0xc410f81d40)
	github.com/Shopify/sarama@v1.36.0/async_producer.go:564 +0x537
github.com/Shopify/sarama.withRecover(0xc27e8bef98?)
	github.com/Shopify/sarama@v1.36.0/utils.go:43 +0x3e
created by github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
	github.com/Shopify/sarama@v1.36.0/async_producer.go:515 +0x1ea
```

**Comment by edoger** [comment]
This problem still exists in the latest version that has been released. The more serious consequence is that the producer will enter a state of stopping work and no longer report any errors. The application usually enters a blocking production state and cannot perceive that the producer has failed.

**Comment by dnwe** [comment]
Fixed in [v1.38.0](https://github.com/IBM/sarama/releases/tag/v1.38.0)
