### ISSUE TITLE
 balance. concurrent map writes

### ISSUE THREAD

**Issue by insulaire** [Shopify/sarama#2422]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.37.2 | 2.2.0 | 1.18 |

##### Configuration

``` go
	s.config = sarama.NewConfig()
	s.config.Version = sarama.V2_2_0_0
	s.config.ChannelBufferSize = 10000
	s.config.ClientID = "server"

	if s.tlsConfig != nil {
		s.config.Net.TLS.Enable = true
		s.config.Net.TLS.Config = s.tlsConfig
	}

	s.config.Net.SASL.User = s.username
	s.config.Net.SASL.Password = s.password

	s.config.Metadata.RefreshFrequency = time.Second * 30

	s.config.Consumer.Retry.BackoffFunc = func(retries int) time.Duration {
		if retries >= 3 {
			return time.Second * 3
		}
		return time.Second
	}
	s.config.Consumer.Fetch.Default = 1024 * 1024
	s.config.Consumer.MaxWaitTime = 100 * time.Millisecond
	s.config.Consumer.Return.Errors = false
	s.config.Consumer.Group.Rebalance.GroupStrategies = []sarama.BalanceStrategy{sarama.BalanceStrategySticky}
	s.config.Consumer.Offsets.AutoCommit.Enable = s.autoCommit
	s.config.Consumer.Offsets.Retention = 24 * time.Hour

	s.config.Consumer.Group.Session.Timeout = 15 * time.Second
	s.config.Consumer.Group.Heartbeat.Interval = 5 * time.Second
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
fatal error: concurrent map writes

goroutine 291 [running]:
runtime.throw({0x36fb26e?, 0xc000000d28?})
	/src/runtime/panic.go:992 +0x76 fp=0xc0025d37f0 sp=0xc0025d37c0 pc=0xb80576
runtime.mapassign(0x3368c20, 0xc002ea8f60, 0xc002d418a0?)
	/src/runtime/map.go:686 +0x5ab fp=0xc0025d3888 sp=0xc0025d37f0 pc=0xb50f6b
github.com/Shopify/sarama.(*partitionMovements).addPartitionMovementRecord(0x4f8e410, {{0xc002d418e0, 0x1d}, 0x2}, {{0xc0042973e0, 0x2b}, {0xc0042973b0, 0x2b}})
	/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/balance_strategy.go:922 +0xba fp=0xc0025d3958 sp=0xc0025d3888 pc=0x16942fa
github.com/Shopify/sarama.(*partitionMovements).movePartition(0x4f8e410, {{0xc002d418e0, 0x1d}, 0x2}, {0xc0042973e0, 0x2b}, {0xc0042973b0, 0x2b})
	/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/balance_strategy.go:952 +0x3ad fp=0xc0025d3a80 sp=0xc0025d3958 pc=0x1694a0d
github.com/Shopify/sarama.(*stickyBalanceStrategy).processPartitionMovement(0x4f8e410, {{0xc002d418e0, 0x1d}, 0x2}, {0xc0042973b0, 0x2b}, 0xc002d7c540, {0xc002d35d00, 0x2, 0x2}, ...)
	/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/balance_strategy.go:564 +0x11b fp=0xc0025d3b80 sp=0xc0025d3a80 pc=0x168f19b
github.com/Shopify/sarama.(*stickyBalanceStrategy).reassignPartition(0x4f8e410, {{0xc002d418e0, 0x1d}, 0x2}, 0xc002d7c540, {0xc002d35d00, 0x2, 0x2}, 0xc0025d4b60, {0xc0042973b0, ...})
	/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/balance_strategy.go:558 +0x191 fp=0xc0025d3c60 sp=0xc0025d3b80 pc=0x168efd1
github.com/Shopify/sarama.(*stickyBalanceStrategy).reassignPartitionToNewConsumer(0x4f8e410, {{0xc002d418e0, 0x1d}, 0x2}, 0xc002d7c540, {0xc002d35d00, 0x2, 0x2}, 0xc0025d4b60, 0xc0025d4b90)
	/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/balance_strategy.go:547 +0x217 fp=0xc0025d3d58 sp=0xc0025d3c60 pc=0x168ed57
github.com/Shopify/sarama.(*stickyBalanceStrategy).performReassignments(0x4f8e410, {0xc003cdf260, 0x3, 0x4}, 0xc002d7c540, 0xc002d7c570, {0xc002d35d00, 0x2, 0x2}, 0xc0025d4b90, ...)
	/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/balance_strategy.go:530 +0x825 fp=0xc0025d3f08 sp=0xc0025d3d58 pc=0x168ea65
github.com/Shopify/sarama.(*stickyBalanceStrategy).balance(0x4f8e410, 0xc002d7c540, 0xc002d7c570, {0xc003cdf260, 0x3, 0x4}, {0x0, 0x0, 0x0}, {0xc002d35d00, ...}, ...)
	/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/balance_strategy.go:322 +0x77d fp=0xc0025d46b0 sp=0xc0025d3f08 pc=0x168d03d
github.com/Shopify/sarama.(*stickyBalanceStrategy).Plan(0x4f8e410, 0xc002d7c480, 0xc002d7c4b0)
	/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/balance_strategy.go:248 +0xc14 fp=0xc0025d5338 sp=0xc0025d46b0 pc=0x168b794
github.com/Shopify/sarama.(*consumerGroup).balance(0xc0000b6840, {0x3db0870, 0x4f8e410}, 0xc002d7c480)
	/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/consumer_group.go:540 +0x39c fp=0xc0025d5578 sp=0xc0025d5338 pc=0x16c58fc
github.com/Shopify/sarama.(*consumerGroup).newSession(0xc0000b6840, {0x3db8e38, 0xc00049ba00}, {0xc002e3fad0, 0x1, 0x1}, {0x3db0480, 0xc000144698}, 0x4)
	/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/consumer_group.go:351 +0xb74 fp=0xc0025d5aa8 sp=0xc0025d5578 pc=0x16c3014
github.com/Shopify/sarama.(*consumerGroup).Consume(0xc0000b6840, {0x3db8e38, 0xc00049ba00}, {0xc002e3fad0, 0x1, 0x1}, {0x3db0480, 0xc000144698})
	/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/consumer_group.go:206 +0x2d3 fp=0xc0025d5c18 sp=0xc0025d5aa8 pc=0x16c1ab3
```

</p>
</details>

**Comment by insulaire** [comment]
Yes, using the same configuration item for multiple consumers.
