### ISSUE TITLE
panic deep in fetchMessages() b/c c.broker is nil when kafka cluster stops

### ISSUE THREAD

**Issue by nsd20463** [Shopify/sarama#245]
I have a reproducible panic in the sarama library.

If we stop the kafka cluster by stopping each broker one by one (in this case our 3 brokers named kafka-000, kafka-001 and kafka-002) the client panics in *Broker.send() because b (the pointer to the Broker) is nil.

This is with the current sarama (74f18a8a1b61b4658b466f7eb07702839e207e0d), go 1.4 on linux/amd64 (tag "go1.4" == 21924:9ef10fde754f), kafka version 0.8.2beta, and rather ordinary client code:

    cl, err := sarama.NewClient("change", []string{*KAFKA_BROKER}, nil)
    ...(error checking elided)...
    partitions, err := cl.Partitions(KAFKA_CHANGE_TOPIC)
    ...
    con_config := sarama.NewConsumerConfig()
    partition := partitions[0]
    con_config.OffsetMethod = sarama.OffsetMethodNewest
    con, err := sarama.NewConsumer(cl, KAFKA_CHANGE_TOPIC, partition, "change_group", con_config)

    for {
        select {
        case ev := <-con.Events():
        ...

The sarama logger out and the panic are:

<start when we stop kafka>
G72 LOG> 19:58:15.883013 consumer.go:191: Unexpected error processing FetchRequest; disconnecting broker kafka-001:6667: EOF
G79 LOG> 19:58:15.883025 consumer.go:191: Unexpected error processing FetchRequest; disconnecting broker kafka-001:6667: EOF
G79 LOG> 19:58:15.883071 client.go:310: Disconnecting Broker 172314977
G79 LOG> 19:58:15.883090 client.go:353: Fetching metadata from broker kafka-000:6667
G79 LOG> 19:58:15.883201 client.go:376: Error from broker while fetching metadata: EOF
G79 LOG> 19:58:15.883224 client.go:310: Disconnecting Broker -1
G79 LOG> 19:58:15.883244 client.go:353: Fetching metadata from broker kafka-002:6667
G86 LOG> 19:58:15.883337 broker.go:134: Closed connection to broker kafka-001:6667
G87 LOG> 19:58:15.883381 broker.go:134: Closed connection to broker kafka-000:6667
G72 LOG> 19:58:15.883403 client.go:310: Disconnecting Broker 172314977
G72 LOG> 19:58:15.883420 client.go:353: Fetching metadata from broker kafka-000:6667
G72 LOG> 19:58:15.883460 client.go:376: Error from broker while fetching metadata: EOF
G72 LOG> 19:58:15.883477 client.go:310: Disconnecting Broker -1
G72 LOG> 19:58:15.883484 client.go:353: Fetching metadata from broker kafka-000:6667
G38 LOG> 19:58:15.883548 broker.go:134: Closed connection to broker kafka-001:6667
G72 LOG> 19:58:15.883575 client.go:376: Error from broker while fetching metadata: EOF
G72 LOG> 19:58:15.883587 client.go:310: Disconnecting Broker 172311936
G72 LOG> 19:58:15.883605 client.go:353: Fetching metadata from broker kafka-002:6667
G39 LOG> 19:58:15.883664 broker.go:134: Closed connection to broker kafka-000:6667
G40 LOG> 19:58:15.883692 broker.go:134: Closed connection to broker kafka-000:6667
G72 LOG> 19:58:15.885591 client.go:517: Registered new broker #172314977 at kafka-001:6667
G79 LOG> 19:58:15.886041 client.go:517: Registered new broker #172314977 at kafka-001:6667
G42 LOG> 19:58:15.887452 broker.go:104: Failed to connect to broker kafka-001:6667
G41 LOG> 19:58:15.887452 broker.go:104: Failed to connect to broker kafka-001:6667
G42 LOG> 19:58:15.887476 broker.go:105: dial tcp 172.31.49.77:6667: connection refused
G41 LOG> 19:58:15.887487 broker.go:105: dial tcp 172.31.49.77:6667: connection refused
G72 LOG> 19:58:15.887508 client.go:365: Some partitions are leaderless, waiting 250ms for election... (3 retries remaining)
G72 LOG> 19:58:16.137710 client.go:353: Fetching metadata from broker kafka-002:6667
G72 LOG> 19:58:16.138882 client.go:365: Some partitions are leaderless, waiting 250ms for election... (2 retries remaining)
G72 LOG> 19:58:16.389092 client.go:353: Fetching metadata from broker kafka-001:6667
G72 LOG> 19:58:16.389149 client.go:376: Error from broker while fetching metadata: dial tcp 172.31.49.77:6667: connection refused
G72 LOG> 19:58:16.389157 client.go:310: Disconnecting Broker 172314977
G72 LOG> 19:58:16.389176 client.go:353: Fetching metadata from broker kafka-002:6667
G43 LOG> 19:58:16.389256 broker.go:136: Failed to close connection to broker kafka-001:6667.
G43 LOG> 19:58:16.389263 broker.go:137: kafka: broker: not connected
G43 LOG> 19:58:16.389344 utils.go:52: Error closing &{172314977 kafka-001:6667 <nil> 0 <nil> 0xc20802b440 {0 0} <nil> <nil>} : 
kafka: broker: not connected
G72 LOG> 19:58:16.390163 client.go:365: Some partitions are leaderless, waiting 250ms for election... (1 retries remaining)
G72 LOG> 19:58:16.640366 client.go:353: Fetching metadata from broker kafka-002:6667
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x45f263]

goroutine 72 [running]:
github.com/Shopify/sarama.(*Broker).send(0x0, 0x790a70, 0x5, 0x7f0597847920, 0xc208166ea0, 0xc208168a01, 0x0, 0x0, 0x0)
        /opt/go/src/github.com/Shopify/sarama/broker.go:259 +0x5c3
github.com/Shopify/sarama.(*Broker).sendAndReceive(0x0, 0x790a70, 0x5, 0x7f0597847920, 0xc208166ea0, 0x7f0597847958, 0xc20808e218, 0x0, 0x0)
        /opt/go/src/github.com/Shopify/sarama/broker.go:297 +0x96
github.com/Shopify/sarama.(*Broker).Fetch(0x0, 0x790a70, 0x5, 0xc208166ea0, 0x5, 0x0, 0x0)
        /opt/go/src/github.com/Shopify/sarama/broker.go:225 +0xef
github.com/Shopify/sarama.(*Consumer).fetchMessages(0xc208116090)
        /opt/go/src/github.com/Shopify/sarama/consumer.go:180 +0x10a
github.com/Shopify/sarama.*Consumer.(github.com/Shopify/sarama.fetchMessages)·fm()
        /opt/go/src/github.com/Shopify/sarama/consumer.go:133 +0x27
github.com/Shopify/sarama.withRecover(0xc20800b710)
        /opt/go/src/github.com/Shopify/sarama/utils.go:45 +0x3a
created by github.com/Shopify/sarama.NewConsumer
        /opt/go/src/github.com/Shopify/sarama/consumer.go:133 +0x58c

**Comment by nsd20463** [comment]
@eapache yes this fixes my panic. Thank you.
