### ISSUE TITLE
Heisenbug

### ISSUE THREAD

**Issue by eapache** [Shopify/sarama#399]
Finally managed to get a stack trace from kafka when creating topics in the test suite, this is the cause of our occasionally randomly failing tests:

```
Error while executing topic command org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids
org.I0Itec.zkclient.exception.ZkNoNodeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids
    at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:47)
    at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:685)
    at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:413)
    at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:409)
    at kafka.utils.ZkUtils$.getChildren(ZkUtils.scala:480)
    at kafka.utils.ZkUtils$.getSortedBrokerList(ZkUtils.scala:81)
    at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:154)
    at kafka.admin.TopicCommand$.createTopic(TopicCommand.scala:86)
    at kafka.admin.TopicCommand$.main(TopicCommand.scala:50)
    at kafka.admin.TopicCommand.main(TopicCommand.scala)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:42)
    at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1249)
    at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1277)
    at org.I0Itec.zkclient.ZkConnection.getChildren(ZkConnection.java:99)
    at org.I0Itec.zkclient.ZkClient$2.call(ZkClient.java:416)
    at org.I0Itec.zkclient.ZkClient$2.call(ZkClient.java:413)
    at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:675)
```

FWIW, this occurred on creating the first topic, while creating the second topic succeeded. I keep bumping the "wait for it to load" sleep call to no effect though, so I'm not sure what's going on.

**Comment by wvanbergen** [comment]
This basically means that no broker is running yet; as part of their startup logic they create an entry in that ZK node. We can wait longer, or poll port 9092.

**Comment by eapache** [comment]
How do we poll port 9092?

**Comment by wvanbergen** [comment]
#dunnolol - is there a default unix tool for this?

**Comment by eapache** [comment]
https://unix.stackexchange.com/questions/5277/how-do-i-tell-a-script-to-wait-for-a-process-to-start-accepting-requests-on-a-po I guess
