### ISSUE TITLE
java.lang.NegativeArraySizeException in Kafka Server when using sarama.CompressionSnappy

### ISSUE THREAD

**Issue by entombedvirus** [Shopify/sarama#702]
##### Versions

Sarama Version: master @ 7fbb591e578ef78a88ed72f3ea7156a086a680be
Kafka Version: 0.10.0.0
Go Version: 1.6.2

##### Configuration

What configuration values are you using for Sarama and Kafka?

Sarama:
```
    saramaConfig := sarama.NewConfig()
	saramaConfig.Producer.Flush.Frequency = 200 * time.Millisecond
	saramaConfig.Producer.Compression = sarama.CompressionSnappy
	saramaConfig.Producer.Partitioner = sarama.NewRandomPartitioner
	saramaConfig.Producer.MaxMessageBytes = 4 * 1024 * 1024 // same as message.max.bytes on kafka server
	saramaConfig.Producer.Return.Successes = true
	saramaConfig.Metadata.RefreshFrequency = 2 * time.Minute
```

Kafka:
```
    request.timeout.ms = 30000
    log.roll.hours = 168
    inter.broker.protocol.version = 0.10.0-IV1
    log.preallocate = false
    security.inter.broker.protocol = PLAINTEXT
    controller.socket.timeout.ms = 30000
    broker.id.generation.enable = true
    ssl.keymanager.algorithm = SunX509
    ssl.key.password = null
    log.cleaner.enable = true
    ssl.provider = null
    num.recovery.threads.per.data.dir = 4
    background.threads = 10
    unclean.leader.election.enable = true
    sasl.kerberos.kinit.cmd = /usr/bin/kinit
    replica.lag.time.max.ms = 10000
    ssl.endpoint.identification.algorithm = null
    sasl.mechanism.inter.broker.protocol = GSSAPI
    auto.create.topics.enable = true
    log.message.timestamp.difference.max.ms = 9223372036854775807
    zookeeper.sync.time.ms = 2000
    ssl.client.auth = none
    ssl.keystore.password = [hidden]
    offsets.topic.compression.codec = 0
    log.cleaner.io.buffer.load.factor = 0.9
    log.retention.hours = 96
    log.dirs = /mnt/ebs1/kafka
    ssl.protocol = TLS
    log.index.size.max.bytes = 10485760
    sasl.kerberos.min.time.before.relogin = 60000
    broker.rack = null
    log.retention.minutes = null
    connections.max.idle.ms = 600000
    ssl.trustmanager.algorithm = PKIX
    offsets.retention.minutes = 1440
    max.connections.per.ip = 2147483647
    replica.fetch.wait.max.ms = 500
    log.message.timestamp.type = CreateTime
    metrics.num.samples = 2
    port = 9092
    offsets.retention.check.interval.ms = 600000
    log.cleaner.dedupe.buffer.size = 134217728
    log.segment.bytes = 1073741824
    group.min.session.timeout.ms = 6000
    producer.purgatory.purge.interval.requests = 1000
    min.insync.replicas = 1
    ssl.truststore.password = [hidden]
    socket.receive.buffer.bytes = 33554432
    log.flush.scheduler.interval.ms = 9223372036854775807
    num.io.threads = 8
    leader.imbalance.per.broker.percentage = 10
    zookeeper.connect = 10.0.0.145:2181,10.0.2.85:2181,10.0.1.104:2181
    queued.max.requests = 500
    offsets.topic.replication.factor = 3
    replica.socket.timeout.ms = 30000
    offsets.topic.segment.bytes = 104857600
    replica.high.watermark.checkpoint.interval.ms = 5000
    broker.id = 1
    ssl.keystore.location = /var/private/ssl/server.keystore.jks
    listeners = PLAINTEXT://:9092,SSL://:9093
    log.flush.interval.messages = 9223372036854775807
    principal.builder.class = class org.apache.kafka.common.security.auth.DefaultPrincipalBuilder
    log.retention.ms = null
    offsets.commit.required.acks = -1
    sasl.kerberos.principal.to.local.rules = [DEFAULT]
    group.max.session.timeout.ms = 300000
    num.replica.fetchers = 1
    advertised.listeners = PLAINTEXT://10.0.0.137:9092,SSL://52.35.99.147:9093
    replica.socket.receive.buffer.bytes = 65536
    delete.topic.enable = true
    log.index.interval.bytes = 4096
    metric.reporters = []
    compression.type = producer
    log.cleanup.policy = delete
    log.message.format.version = 0.10.0-IV1
    controlled.shutdown.max.retries = 3
    log.cleaner.threads = 1
    quota.window.size.seconds = 1
    zookeeper.connection.timeout.ms = 6000
    offsets.load.buffer.size = 5242880
    zookeeper.session.timeout.ms = 6000
    ssl.cipher.suites = null
    authorizer.class.name =
    sasl.kerberos.ticket.renew.jitter = 0.05
    sasl.enabled.mechanisms = [GSSAPI]
    sasl.kerberos.service.name = null
    controlled.shutdown.enable = true
    offsets.topic.num.partitions = 50
    quota.window.num = 11
    message.max.bytes = 4194304
    log.cleaner.backoff.ms = 15000
    log.roll.jitter.hours = 0
    log.retention.check.interval.ms = 300000
    replica.fetch.max.bytes = 4194304
    log.cleaner.delete.retention.ms = 86400000
    fetch.purgatory.purge.interval.requests = 1000
    log.cleaner.min.cleanable.ratio = 0.5
    offsets.commit.timeout.ms = 5000
    zookeeper.set.acl = false
    log.retention.bytes = -1
    offset.metadata.max.bytes = 4096
    leader.imbalance.check.interval.seconds = 300
    quota.consumer.default = 9223372036854775807
    log.roll.jitter.ms = null
    reserved.broker.max.id = 1000
    replica.fetch.backoff.ms = 1000
    advertised.host.name = null
    quota.producer.default = 9223372036854775807
    log.cleaner.io.buffer.size = 524288
    controlled.shutdown.retry.backoff.ms = 5000
    log.dir = /tmp/kafka-logs
    log.flush.offset.checkpoint.interval.ms = 60000
    log.segment.delete.delay.ms = 60000
    num.partitions = 512
    num.network.threads = 3
    socket.request.max.bytes = 104857600
    sasl.kerberos.ticket.renew.window.factor = 0.8
    log.roll.ms = null
    ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
    socket.send.buffer.bytes = 33554432
    log.flush.interval.ms = 1000
    ssl.truststore.location = /var/private/ssl/server.truststore.jks
    log.cleaner.io.max.bytes.per.second = 1.7976931348623157E308
    default.replication.factor = 1
    metrics.sample.window.ms = 30000
    auto.leader.rebalance.enable = true
    host.name =
    ssl.truststore.type = JKS
    advertised.port = null
    max.connections.per.ip.overrides =
    replica.fetch.min.bytes = 1
    ssl.keystore.type = JKS
```

##### Logs

Kafka server.log
```
[2016-07-12 23:26:03,519] ERROR [Replica Manager on Broker 1]: Error processing append operation on partition engage.3-30 (kafka.server.ReplicaManager)
kafka.common.KafkaException:
    at kafka.message.ByteBufferMessageSet$$anon$1.makeNext(ByteBufferMessageSet.scala:159)
    at kafka.message.ByteBufferMessageSet$$anon$1.makeNext(ByteBufferMessageSet.scala:85)
    at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:64)
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:56)
    at kafka.message.ByteBufferMessageSet$$anon$2.makeNextOuter(ByteBufferMessageSet.scala:357)
    at kafka.message.ByteBufferMessageSet$$anon$2.makeNext(ByteBufferMessageSet.scala:369)
    at kafka.message.ByteBufferMessageSet$$anon$2.makeNext(ByteBufferMessageSet.scala:324)
    at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:64)
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:56)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at kafka.utils.IteratorTemplate.foreach(IteratorTemplate.scala:30)
    at kafka.message.ByteBufferMessageSet.validateMessagesAndAssignOffsets(ByteBufferMessageSet.scala:427)
    at kafka.log.Log.liftedTree1$1(Log.scala:339)
    at kafka.log.Log.append(Log.scala:338)
    at kafka.cluster.Partition$$anonfun$11.apply(Partition.scala:443)
    at kafka.cluster.Partition$$anonfun$11.apply(Partition.scala:429)
    at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:231)
    at kafka.utils.CoreUtils$.inReadLock(CoreUtils.scala:237)
    at kafka.cluster.Partition.appendMessagesToLeader(Partition.scala:429)
    at kafka.server.ReplicaManager$$anonfun$appendToLocalLog$2.apply(ReplicaManager.scala:406)
    at kafka.server.ReplicaManager$$anonfun$appendToLocalLog$2.apply(ReplicaManager.scala:392)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
    at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
    at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
    at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at kafka.server.ReplicaManager.appendToLocalLog(ReplicaManager.scala:392)
    at kafka.server.ReplicaManager.appendMessages(ReplicaManager.scala:328)
    at kafka.server.KafkaApis.handleProducerRequest(KafkaApis.scala:405)
    at kafka.server.KafkaApis.handle(KafkaApis.scala:76)
    at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: failed to read chunk
    at org.xerial.snappy.SnappyInputStream.hasNextChunk(SnappyInputStream.java:433)
    at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:167)
    at java.io.DataInputStream.readFully(DataInputStream.java:195)
    at java.io.DataInputStream.readLong(DataInputStream.java:416)
    at kafka.message.ByteBufferMessageSet$$anon$1.readMessageFromStream(ByteBufferMessageSet.scala:118)
    at kafka.message.ByteBufferMessageSet$$anon$1.makeNext(ByteBufferMessageSet.scala:153)
    ... 35 more
[2016-07-12 23:26:06,047] ERROR [Replica Manager on Broker 1]: Error processing append operation on partition track.3-77 (kafka.server.ReplicaManager)
java.lang.NegativeArraySizeException
    at org.xerial.snappy.SnappyInputStream.hasNextChunk(SnappyInputStream.java:422)
    at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:167)
    at java.io.DataInputStream.readFully(DataInputStream.java:195)
    at java.io.DataInputStream.readLong(DataInputStream.java:416)
    at kafka.message.ByteBufferMessageSet$$anon$1.readMessageFromStream(ByteBufferMessageSet.scala:118)
    at kafka.message.ByteBufferMessageSet$$anon$1.makeNext(ByteBufferMessageSet.scala:153)
    at kafka.message.ByteBufferMessageSet$$anon$1.makeNext(ByteBufferMessageSet.scala:85)
    at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:64)
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:56)
    at kafka.message.ByteBufferMessageSet$$anon$2.makeNextOuter(ByteBufferMessageSet.scala:357)
    at kafka.message.ByteBufferMessageSet$$anon$2.makeNext(ByteBufferMessageSet.scala:369)
    at kafka.message.ByteBufferMessageSet$$anon$2.makeNext(ByteBufferMessageSet.scala:324)
    at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:64)
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:56)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at kafka.utils.IteratorTemplate.foreach(IteratorTemplate.scala:30)
    at kafka.message.ByteBufferMessageSet.validateMessagesAndAssignOffsets(ByteBufferMessageSet.scala:427)
    at kafka.log.Log.liftedTree1$1(Log.scala:339)
    at kafka.log.Log.append(Log.scala:338)
    at kafka.cluster.Partition$$anonfun$11.apply(Partition.scala:443)
    at kafka.cluster.Partition$$anonfun$11.apply(Partition.scala:429)
    at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:231)
    at kafka.utils.CoreUtils$.inReadLock(CoreUtils.scala:237)
    at kafka.cluster.Partition.appendMessagesToLeader(Partition.scala:429)
    at kafka.server.ReplicaManager$$anonfun$appendToLocalLog$2.apply(ReplicaManager.scala:406)
    at kafka.server.ReplicaManager$$anonfun$appendToLocalLog$2.apply(ReplicaManager.scala:392)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
    at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
    at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
    at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at kafka.server.ReplicaManager.appendToLocalLog(ReplicaManager.scala:392)
    at kafka.server.ReplicaManager.appendMessages(ReplicaManager.scala:328)
    at kafka.server.KafkaApis.handleProducerRequest(KafkaApis.scala:405)
    at kafka.server.KafkaApis.handle(KafkaApis.scala:76)
    at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
    at java.lang.Thread.run(Thread.java:745)
```

No errors in sarama logger.

##### Problem Description

When using `sarama.CompressionSnappy` in sarama against Kafka v0.10.0.0, Kafka `server.log` is flooded with `java.lang.NegativeArraySizeException`. Errors go away if I switch to using `sarama.CompressionGZIP`. I am using TLS between the producer and kafka.

**Comment by eapache** [comment]
I believe this is the upstream bug https://issues.apache.org/jira/browse/KAFKA-3789. Try upgrading the `snappy-java` package on the broker, or wait for Kafka 0.10.0.1.
