### ISSUE TITLE
Client has run out of available brokers to talk to (Is your cluster reachable?)

### ISSUE THREAD

**Issue by derekssmith** [Shopify/sarama#731]
Sarama Version: v1
Kafka Version: 0.10.0
Go Version: 1.6.2

I am having an issue creating a  consumer against a local kafka cluster.  All of a sudden I started receiving an error when trying to create a new consumer.  The error is **kafka: client has run out of available brokers to talk to (Is your cluster reachable?)**.  I am running producers against this cluster, as well as using the consumergroup library from [github.com/wvanbergen/kafka/consumergroup](github.com/wvanbergen/kafka/consumergroup), with no problems.

The simple code below:

```go
package main

import "gopkg.in/Shopify/sarama.v1"

func main() {

	_, err := sarama.NewConsumer([]string{"127.0.0.1:2181"}, nil)
	if err != nil {
		panic(err)
	}

}
```

Results in this output:

```
panic: kafka: client has run out of available brokers to talk to (Is your clu           
ster reachable?)                                                                        
                                                                                        
goroutine 1 [running]:                                                                  
panic(0x6a44c0, 0xc82000ab70)                                                           
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6                                 
main.main()                                                                             
        /home/derek/work/src/tempuri.org/kafkatest/main.go:9 +0xac                      
exit status 2    
```

Through some debugging this issue appears to happen in the `NewClient(addrs, config)` call that is made at the top of the `NewConsumer()` function.  Tracing further leads me to an error during the refresh metadata retry loop.  The error that is being returned from that call is an `EOF` error.

Not sure how to proceed.

**Comment by derekssmith** [comment]
Nevermind, I realized my mistake.
