### ISSUE TITLE
panic: sync: WaitGroup is reused before previous Wait has returned

### ISSUE THREAD

**Issue by krisoul** [Shopify/sarama#883]
```
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 94911 [running]:
sync.(*WaitGroup).Wait(0xc420157fc0)
	/home/lvzhuo/packages/go/src/sync/waitgroup.go:133 +0xd8
github.com/Shopify/sarama.(*asyncProducer).shutdown(0xc420157f80)
	/data/lvzhuo/workspace/go/src/github.com/Shopify/sarama/async_producer.go:810 +0x147
github.com/Shopify/sarama.(*asyncProducer).(github.com/Shopify/sarama.shutdown)-fm()
	/data/lvzhuo/workspace/go/src/github.com/Shopify/sarama/async_producer.go:223 +0x2a
github.com/Shopify/sarama.withRecover(0xc420ff8b70)
	/data/lvzhuo/workspace/go/src/github.com/Shopify/sarama/utils.go:46 +0x43
created by github.com/Shopify/sarama.(*asyncProducer).AsyncClose
	/data/lvzhuo/workspace/go/src/github.com/Shopify/sarama/async_producer.go:223 +0x7b
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 94912 [running]:
sync.(*WaitGroup).Wait(0xc420157fc0)
	/home/lvzhuo/packages/go/src/sync/waitgroup.go:133 +0xd8
github.com/Shopify/sarama.(*asyncProducer).shutdown(0xc420157f80)
	/data/lvzhuo/workspace/go/src/github.com/Shopify/sarama/async_producer.go:810 +0x147
github.com/Shopify/sarama.(*asyncProducer).(github.com/Shopify/sarama.shutdown)-fm()
	/data/lvzhuo/workspace/go/src/github.com/Shopify/sarama/async_producer.go:223 +0x2a
github.com/Shopify/sarama.withRecover(0xc420ff8ba0)
	/data/lvzhuo/workspace/go/src/github.com/Shopify/sarama/utils.go:46 +0x43
created by github.com/Shopify/sarama.(*asyncProducer).AsyncClose
	/data/lvzhuo/workspace/go/src/github.com/Shopify/sarama/async_producer.go:223 +0x7b

```

How to solve this?

**Comment by eapache** [comment]
Somewhere your app is making multiple simultaneous calls to `AsyncClose`. You can't do that.
